---
- name: Ensure docker users are added to the docker group.
  user:
    name: "{{ item }}"
    groups: docker
    append: true
  with_items: "{{ docker_users }}"

- name: Create docker config dir in users home
  file:
    path: "~{{ item }}/.docker"
    state: directory
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0700
  with_items: "{{ docker_users }}"

- name: Copy docker client config into user home
  copy:
    content: "{{ docker_config_json | to_nice_json(indent=2) }}"
    dest: "~{{ item }}/.docker/config.json"
    mode: 0600
    owner: "{{ item }}"
    group: "{{ item }}"
  with_items: "{{ docker_users }}"
  register: docker_config_json_apply
  changed_when: docker_config_json_apply.changed
  notify: restart docker
  when: docker_config_json | length > 0
