---
- include_tasks: repo-RedHat.yml
  when: ansible_os_family == 'RedHat' and docker_install_repo | default('true')

- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: repo-Debian.yml
  when: ansible_os_family == 'Debian' and docker_install_repo | default('true')

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: docker-users.yml
  when: docker_users | length > 0

- name: Check data dir Docker
  file:
    path: "{{ docker_data_root }}"
    state: directory
  when: docker_data_root | length > 0

- name: Add group "docker"
  group:
    name: docker
    state: present

- name: Config Docker via daemon.json
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
  register: docker_daemon_json
  changed_when: docker_daemon_json.changed
  notify: restart docker
  when: docker_private_repo_auth_host | length > 0 or docker_custom_registry | length > 0

- name: Ensure Docker is started and enabled at boot.
  systemd:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"
