---
- name: Ensure old versions of Docker are not installed.
  package:
    name:
      - docker
      - docker-common
      - docker-engine
    state: absent

- name: Install required packages for Docker (RedHat)
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
      - container-selinux
    state: "{{ docker_package_state }}"

- name: Check "{{ docker_package }}" package is installed (CentOS 7)
  yum:
    name: "{{ docker_package }}"
    state: "{{ docker_package_state }}"
